/**
 * Crier has no live Amazon category-tree or keyword-research API — same
 * constraint as Loom, nothing is authorized in CLAUDE.md. So listing copy
 * is built from data already produced earlier in the pipeline (theme,
 * suggested angle, page count) plus a couple of generic, real KDP
 * category names, not invented market data.
 *
 * buildTitle/buildSubtitle take an IllustrationStyle so a batch's cover
 * art (built by Loom, see agents/loom/templates.ts's buildCoverPrompt)
 * and its listing.json title never diverge — Loom imports buildTitle
 * directly rather than each side building its own title text. Keywords,
 * categories, and description below are still coloring-book-only; v2's
 * multi-category expansion generalizes title/subtitle first since Loom's
 * cover art depends on them, but the rest of Crier still needs the same
 * treatment before non-coloring-book batches get a correct listing.
 */
import type { IllustrationStyle } from "../../schemas/manifest.ts";

/** Deterministic keyword-phrase variants derived from the theme text itself. */
function generateKeywordVariants(theme: string): string[] {
  const t = theme.trim();
  const variants = [
    `${t} coloring book`,
    `${t} coloring pages`,
    `adult ${t} coloring book`,
    `${t} coloring book for kids`,
    `easy ${t} coloring book`,
    `detailed ${t} coloring pages`,
  ];
  return Array.from(new Set(variants.map((v) => v.trim())));
}

export const MAX_KEYWORD_LENGTH = 50;

export const DEFAULT_CATEGORIES = [
  "Crafts, Hobbies & Home > Crafts & Hobbies > Coloring Books for Grown-Ups",
  "Humor & Entertainment > Puzzles & Games > Coloring Books for Grown-Ups",
];

const GENERIC_KEYWORDS = [
  "relaxation coloring book for adults",
  "stress relief coloring pages",
  "line art coloring book",
];

/** Truncates at the last whole word that fits, so a keyword never ends mid-word. */
export function truncate(value: string, maxLength: number): string {
  if (value.length <= maxLength) {
    return value;
  }
  const cut = value.slice(0, maxLength);
  const lastSpace = cut.lastIndexOf(" ");
  return (lastSpace > 0 ? cut.slice(0, lastSpace) : cut).trimEnd();
}

/** Builds exactly 7 unique keyword phrases, reusing Scout's variants plus generic fallbacks. */
export function buildKeywords(theme: string): string[] {
  const candidates = [...generateKeywordVariants(theme), ...GENERIC_KEYWORDS].map((k) =>
    truncate(k, MAX_KEYWORD_LENGTH)
  );
  const unique = Array.from(new Set(candidates));
  if (unique.length < 7) {
    throw new Error(
      `Crier: could not generate 7 unique keyword phrases for theme "${theme}" (only found ${unique.length}).`
    );
  }
  return unique.slice(0, 7);
}

const DEFAULT_ILLUSTRATION_STYLE: IllustrationStyle = "coloring-book";

export function buildTitle(theme: string, illustrationStyle: IllustrationStyle = DEFAULT_ILLUSTRATION_STYLE): string {
  switch (illustrationStyle) {
    case "picture-book":
      return `${theme}: A Picture Book`;
    case "coloring-book":
      return `${theme}: A Coloring Book`;
  }
}

export function buildSubtitle(
  theme: string,
  pageCount: number,
  illustrationStyle: IllustrationStyle = DEFAULT_ILLUSTRATION_STYLE
): string {
  switch (illustrationStyle) {
    case "picture-book":
      return `A ${pageCount}-Page Illustrated Picture Book About ${theme}`;
    case "coloring-book":
      return `${pageCount} Original ${theme} Coloring Pages for Relaxation`;
  }
}

export function buildDescription(theme: string, pageCount: number, suggestedAngle: string): string {
  return [
    `Escape into ${pageCount} original ${theme.toLowerCase()} illustrations designed for relaxed, unhurried coloring.`,
    `Each page is bold-outlined and printed single-sided on its own sheet — no color bleed-through, just room to create.`,
    suggestedAngle,
    `Whether you're coloring to unwind after a long day or looking for a thoughtful gift, this collection offers a fresh page every time.`,
  ].join("\n\n");
}

export const AI_DISCLOSURE_NOTE =
  "This listing's title, subtitle, keywords, categories, and description were generated by an AI pipeline (Crier) and require human review before publishing. Amazon KDP requires AI-generated content to be disclosed at the point of publishing.";

export const CATEGORY_NOTE =
  "Suggested defaults, not a live category-tree lookup — confirm the exact category path in KDP's category picker at publish time, since Amazon's category tree can change.";
