import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { MANUSCRIPT_SECTION_COUNT } from "../../config.ts";
import { validateManifest, type BatchManifest } from "../../schemas/manifest.ts";
import { AnthropicWriterClient, type Manuscript, type WriterClient } from "./claudeClient.ts";

export interface WriterRunOptions {
  batchesDir?: string;
  sectionCount?: number;
  /** Injected for tests; defaults to a real Anthropic-backed client. */
  client?: WriterClient;
}

export interface WriterRunResult {
  batchDir: string;
  manifest: BatchManifest;
  manuscriptMdPath: string;
  manuscriptJsonPath: string;
}

interface ManuscriptSectionEntry {
  index: number;
  title: string;
  body: string;
}

interface ManuscriptFile {
  batchId: string;
  theme: string;
  category: string;
  generatedAt: string;
  frontMatterDraft: string;
  backMatterDraft: string;
  sections: ManuscriptSectionEntry[];
}

const EXCERPT_MAX_CHARS = 280;

/** Truncates at the last whole word that fits, so an excerpt never ends mid-word. */
function buildExcerpt(text: string): string {
  const trimmed = text.trim();
  if (trimmed.length <= EXCERPT_MAX_CHARS) {
    return trimmed;
  }
  const cut = trimmed.slice(0, EXCERPT_MAX_CHARS);
  const lastSpace = cut.lastIndexOf(" ");
  return `${(lastSpace > 0 ? cut.slice(0, lastSpace) : cut).trimEnd()}…`;
}

function countWords(manuscript: Manuscript): number {
  return manuscript.sections.reduce((sum, s) => sum + s.body.trim().split(/\s+/).filter(Boolean).length, 0);
}

function renderMarkdown(file: ManuscriptFile): string {
  const { theme, category, frontMatterDraft, backMatterDraft, sections } = file;
  return `# ${theme}

*${category}*

---

## Front Matter (draft)

${frontMatterDraft}

---

${sections.map((s) => `## ${s.title}\n\n${s.body}`).join("\n\n---\n\n")}

---

## Back Matter (draft)

${backMatterDraft}

---

This manuscript was generated by the Anthropic API (see CLAUDE.md's
Authorized external APIs section) — every section above is fully
AI-generated text. It warrants a closer human read than an illustrated
batch before publishing; there is no separate approval gate beyond the
usual pull request review.
`;
}

export async function runWriter(batchId: string, options: WriterRunOptions = {}): Promise<WriterRunResult> {
  const batchesDir = options.batchesDir ?? "batches";
  const sectionCount = options.sectionCount ?? MANUSCRIPT_SECTION_COUNT;
  const client = options.client ?? new AnthropicWriterClient();

  if (sectionCount < 1) {
    throw new Error("Writer section count must be at least 1.");
  }

  const batchDir = join(batchesDir, batchId);
  const manifestPath = join(batchDir, "manifest.json");
  if (!existsSync(manifestPath)) {
    throw new Error(`No batch found at ${batchDir} — run Scout first.`);
  }

  const existingManifest = validateManifest(JSON.parse(readFileSync(manifestPath, "utf-8")));
  if (existingManifest.stage !== "researched") {
    throw new Error(
      `Batch "${batchId}" is at stage "${existingManifest.stage}", but Writer requires stage "researched". Run Scout first.`
    );
  }

  const contentType = existingManifest.opportunityScanner?.contentType;
  if (contentType !== "text") {
    throw new Error(
      `Batch "${batchId}" is a "${contentType ?? "unknown"}" category, but Writer only runs on text-only ("text") categories. Use Loom + Etch for illustrated categories instead.`
    );
  }

  const category = existingManifest.opportunityScanner?.category ?? "text-only book";
  const theme = existingManifest.theme;
  const generatedAt = new Date().toISOString();

  const manuscript = await client.generateManuscript(category, theme, sectionCount);
  const firstSection = manuscript.sections[0];
  if (!firstSection) {
    throw new Error(`Writer: Claude returned a manuscript with zero sections for batch "${batchId}".`);
  }

  const manuscriptFile: ManuscriptFile = {
    batchId,
    theme,
    category,
    generatedAt,
    frontMatterDraft: manuscript.frontMatterDraft,
    backMatterDraft: manuscript.backMatterDraft,
    sections: manuscript.sections.map((s, i) => ({ index: i + 1, title: s.title, body: s.body })),
  };

  const manuscriptJsonPath = join(batchDir, "manuscript.json");
  const manuscriptMdPath = join(batchDir, "manuscript.md");
  writeFileSync(manuscriptJsonPath, JSON.stringify(manuscriptFile, null, 2));
  writeFileSync(manuscriptMdPath, renderMarkdown(manuscriptFile));

  const wordCount = countWords(manuscript);
  const excerpt = buildExcerpt(firstSection.body);

  const manifestCandidate: BatchManifest = {
    ...existingManifest,
    stage: "manuscripted",
    updatedAt: generatedAt,
    writer: {
      manuscriptMdPath,
      manuscriptJsonPath,
      sectionCount: manuscript.sections.length,
      wordCount,
      excerpt,
      aiGeneratedDisclosure: true,
      proofreadRecommended: true,
      completedAt: generatedAt,
    },
  };

  const manifest = validateManifest(manifestCandidate);
  writeFileSync(manifestPath, JSON.stringify(manifest, null, 2));

  return { batchDir, manifest, manuscriptMdPath, manuscriptJsonPath };
}
