import { execFileSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { AnthropicSentinelClient, type Diagnosis, type SentinelClient, type SourceFile } from "./claudeClient.ts";
import { extractCandidateFiles } from "./extractFiles.ts";

/** Keeps the prompt (and token cost) bounded — the tail of a log is almost always where the real error is. */
const MAX_LOG_CHARS = 12_000;
/** Per-file cap so one huge file can't blow the prompt budget. */
const MAX_FILE_CHARS = 6_000;

export interface SentinelRunOptions {
  failureLog: string;
  repoRoot?: string;
  reportPath?: string;
  sentinelClient?: SentinelClient;
  /** Injected for tests; defaults to running `git apply` for real against repoRoot. */
  applyPatch?: (patch: string, repoRoot: string) => void;
}

export interface SentinelRunResult {
  summary: string;
  diagnosis: string;
  confidentFix: boolean;
  patchApplied: boolean;
  reportPath: string;
}

function readCandidateFiles(paths: string[], repoRoot: string): SourceFile[] {
  return paths.map((path) => {
    const full = join(repoRoot, path);
    const content = readFileSync(full, "utf-8").slice(0, MAX_FILE_CHARS);
    return { path, content };
  });
}

function renderReport(diagnosis: Diagnosis, patchApplied: boolean): string {
  return `# Sentinel report: ${diagnosis.summary}

## Diagnosis

${diagnosis.diagnosis}

## Proposed fix

${
  diagnosis.confidentFix
    ? patchApplied
      ? "Sentinel applied the patch below to this branch."
      : "Sentinel proposed the patch below, but it failed to apply cleanly — see the CI job log for the git apply error. No changes were made."
    : "Sentinel was not confident enough in a specific fix to propose a patch. A human should investigate the diagnosis above."
}

${diagnosis.patch ? `\`\`\`diff\n${diagnosis.patch}\n\`\`\`\n` : ""}
---
This diagnosis and patch were generated by the Anthropic API (see CLAUDE.md's Authorized external APIs section). Never auto-merged — a human reviews every change Sentinel proposes, like every other agent's output.
`;
}

function realApplyPatch(patch: string, repoRoot: string): void {
  try {
    execFileSync("git", ["apply", "--whitespace=fix"], { cwd: repoRoot, input: patch, stdio: ["pipe", "pipe", "pipe"] });
  } catch (err) {
    const stderr = err && typeof err === "object" && "stderr" in err ? String((err as { stderr: unknown }).stderr) : "";
    throw new Error(`Sentinel: proposed patch failed to apply (git apply): ${stderr || (err instanceof Error ? err.message : err)}`);
  }
}

/**
 * Diagnoses a CI failure via the Anthropic API and, only when confident,
 * applies a proposed fix to the working tree — never commits or opens a
 * PR itself (the calling GitHub Actions workflow does that, so a human
 * always reviews before anything merges). Fails loudly if the proposed
 * patch doesn't apply cleanly, rather than silently skipping it or
 * fabricating a "fixed" result; the report written just before that
 * point is preserved either way.
 */
export async function runSentinel(options: SentinelRunOptions): Promise<SentinelRunResult> {
  const repoRoot = options.repoRoot ?? process.cwd();
  const reportPath = options.reportPath ?? join(repoRoot, "sentinel-report.md");
  const client = options.sentinelClient ?? new AnthropicSentinelClient();
  const applyPatch = options.applyPatch ?? realApplyPatch;

  const failureLog = options.failureLog.slice(-MAX_LOG_CHARS);
  const candidatePaths = extractCandidateFiles(options.failureLog, repoRoot);
  const files = readCandidateFiles(candidatePaths, repoRoot);

  const diagnosis = await client.diagnose({ failureLog, files });

  let patchApplied = false;
  // Write the report before attempting to apply the patch, so a failed
  // apply still leaves the diagnosis on disk for a human/CI artifact.
  writeFileSync(reportPath, renderReport(diagnosis, patchApplied));

  if (diagnosis.confidentFix) {
    applyPatch(diagnosis.patch, repoRoot);
    patchApplied = true;
    writeFileSync(reportPath, renderReport(diagnosis, patchApplied));
  }

  return {
    summary: diagnosis.summary,
    diagnosis: diagnosis.diagnosis,
    confidentFix: diagnosis.confidentFix,
    patchApplied,
    reportPath,
  };
}
